version: '3'
services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
      - nginx-net
      
networks:
  nginx-net:
    driver: bridge
